version: '3'
services:
  nats-streaming:
    image: 'nats-streaming'
    ports:
      - "4222:4222"
      - "8222:8222"
    entrypoint:
      - /nats-streaming-server
    restart: always
    networks:
      - nats-streaming-network

  pgsql:
    image: 'postgres:14'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'pgsql:/var/lib/postgresql/data'
    networks:
      - postgres-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
      retries: 3
      timeout: 5s

  subscription-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: [ pgsql, nats-streaming ]
    networks:
      - nats-streaming-network
      - postgres-network
    restart: always

networks:
  postgres-network:
    driver: bridge
  nats-streaming-network:
    driver: bridge

volumes:
  pgsql:
    driver: local